---
title: "TAS Descriptive Time Series analysis by location"
author: "Shu Wei"
date: "5/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=3, fig.height=3)
```

```{r, include = FALSE}
library(tidyverse)
library(fracdiff)
library(ggplot2)
library(ggcorrplot)
library(corrplot)
library(RColorBrewer)
library(forecast)
library(fpp2)
library(ggfortify)
library(dplR)
library(wavethresh)
library(WaveletComp)
library(astsa)
```

Reading data

```{r}
load(file ="tas.Rdata")
str(tas.data)
```

# TAS Descriptive: Time Series analysis by location

There are 144 x-coordinates and 115 y-coordinates. We select 9 locations:

```{r}
#set 9 locations (approximately)
y1 <- tas.data %>% filter(lat>=29.97 & lat<=30 & lon>=240 & lon <=241)
y2 <- tas.data %>% filter(lat>=29.87 & lat<=30 & lon>=260.7 & lon <=261)
y3 <- tas.data %>% filter(lat>=29.87 & lat<=30 & lon>=293)

y4 <- tas.data %>% filter(lat>=40 & lat<=41 & lon>=240.9 & lon <=241)
y5 <- tas.data %>% filter(lat>=40 & lat<=41 & lon>=260.65 & lon <=261)
y6 <- tas.data %>% filter(lat>=40 & lat<=41 & lon>=293 & lon <=293.2)

y7 <- tas.data %>% filter(lat>=50 & lat<=51 & lon>=240.7 & lon <=241)
y8 <- tas.data %>% filter(lat>=50 & lat<=51 & lon>=260.65 & lon <=261)
y9 <- tas.data %>% filter(lat>=50 & lat<=51 & lon>=300.8 & lon <=301)

datos <- data.frame(y1[,1:3],y2$tas,y3$tas,y4$tas,y5$tas,y6$tas,y7$tas,y8$tas,y9$tas)
colnames(datos)[3:11]<-c("y1","y2","y3","y4","y5","y6","y7","y8","y9")
names(datos)
```

```{r}
datos.ts<-ts(datos[,-c(1,2)],start=c(1968,1),frequency = 12)
autoplot(datos.ts)
autoplot(datos.ts, facets = TRUE)
```

```{r}
(corr<-cor(datos.ts))
#ggcorrplot(corr)
corrplot(corr, type="upper", order="hclust",
         col=brewer.pal(n=8, name="RdYlBu"))
```


```{r}
y1<-datos.ts[,"y1"]
y2<-datos.ts[,"y2"]
y3<-datos.ts[,"y3"]
y4<-datos.ts[,"y4"]
y5<-datos.ts[,"y5"]
y6<-datos.ts[,"y6"]
y7<-datos.ts[,"y7"]
y8<-datos.ts[,"y8"]
y9<-datos.ts[,"y9"]

gglagplot(y1)
#gglagplot(y2)
#gglagplot(y3)
#gglagplot(y4)
#gglagplot(y5)
#gglagplot(y6)
#gglagplot(y7)
#gglagplot(y8)
#gglagplot(y9)
```

# Autocorrelation:

```{r,fig.width=6, fig.height=6}
par(mfrow=c(3,3))
acf(y1,lag.max=100,ci=0.95)
acf(y2,lag.max=100,ci=0.95)
acf(y3,lag.max=100,ci=0.95)
acf(y4,lag.max=100,ci=0.95)
acf(y5,lag.max=100,ci=0.95)
acf(y6,lag.max=100,ci=0.95)
acf(y7,lag.max=100,ci=0.95)
acf(y8,lag.max=100,ci=0.95)
acf(y9,lag.max=100,ci=0.95)
```


## Location 1

```{r}
autoplot(y1)
ggAcf(y1,lag.max=100,ci=0.95)
ggPacf(y1,lag.max=100,ci=0.95)
ggseasonplot(y1, year.labels=FALSE, continuous=TRUE)
```

# SARIMA:

```{r}
for(i in 1:9){
  show(paste0('Y',i))
mod<-auto.arima(get(paste0("y",i)))
print(mod)
}
```

# Spectral Analysis

```{r ,fig.width=6, fig.height=3}
raw.spec <- spec.pgram(y1, taper = 0)
par(mfrow=c(1,2))
plot(raw.spec)   #log scale
plot(raw.spec, log = "no")

ts.plot(datos.ts, col=1:9)
spec = mvspec(datos.ts, spans=c(3,3), taper=.1)
```


# Wavelets analysis

The WaveletCompu library uses Morlet wavelets.

y1:
```{r,include=FALSE}
my.data <- data.frame(datos.ts)
my.w1 <- analyze.wavelet(my.data, "y1",loess.span = 0,
                  dt = 1, dj = 1/250,lowerPeriod = 1,
              upperPeriod = 128,make.pval = TRUE, n.sim = 10)
my.w2 <- analyze.wavelet(my.data, "y2",loess.span = 0,
                  dt = 1, dj = 1/250,lowerPeriod = 1,
              upperPeriod = 128,make.pval = TRUE, n.sim = 10)
my.w3 <- analyze.wavelet(my.data, "y3",loess.span = 0,
                  dt = 1, dj = 1/250,lowerPeriod = 1,
              upperPeriod = 128,make.pval = TRUE, n.sim = 10)
my.w4 <- analyze.wavelet(my.data, "y4",loess.span = 0,
                  dt = 1, dj = 1/250,lowerPeriod = 1,
              upperPeriod = 128,make.pval = TRUE, n.sim = 10)
my.w5 <- analyze.wavelet(my.data, "y5",loess.span = 0,
                  dt = 1, dj = 1/250,lowerPeriod = 1,
              upperPeriod = 128,make.pval = TRUE, n.sim = 10)
my.w6 <- analyze.wavelet(my.data, "y6",loess.span = 0,
                  dt = 1, dj = 1/250,lowerPeriod = 1,
              upperPeriod = 128,make.pval = TRUE, n.sim = 10)
my.w7 <- analyze.wavelet(my.data, "y7",loess.span = 0,
                  dt = 1, dj = 1/250,lowerPeriod = 1,
              upperPeriod = 128,make.pval = TRUE, n.sim = 10)
my.w8 <- analyze.wavelet(my.data, "y8",loess.span = 0,
                  dt = 1, dj = 1/250,lowerPeriod = 1,
              upperPeriod = 128,make.pval = TRUE, n.sim = 10)
my.w9 <- analyze.wavelet(my.data, "y9",loess.span = 0,
                  dt = 1, dj = 1/250,lowerPeriod = 1,
              upperPeriod = 128,make.pval = TRUE, n.sim = 10)
```


```{r ,fig.width=5, fig.height=5}
wt.image(my.w1, color.key = "quantile", n.levels = 250,
legend.params = list(lab = "wavelet power levels", mar = 4.7))
wt.image(my.w2, color.key = "quantile", n.levels = 250,
legend.params = list(lab = "wavelet power levels", mar = 4.7))
wt.image(my.w3, color.key = "quantile", n.levels = 250,
legend.params = list(lab = "wavelet power levels", mar = 4.7))
wt.image(my.w4, color.key = "quantile", n.levels = 250,
legend.params = list(lab = "wavelet power levels", mar = 4.7))
wt.image(my.w5, color.key = "quantile", n.levels = 250,
legend.params = list(lab = "wavelet power levels", mar = 4.7))
wt.image(my.w6, color.key = "quantile", n.levels = 250,
legend.params = list(lab = "wavelet power levels", mar = 4.7))
wt.image(my.w7, color.key = "quantile", n.levels = 250,
legend.params = list(lab = "wavelet power levels", mar = 4.7))
wt.image(my.w8, color.key = "quantile", n.levels = 250,
legend.params = list(lab = "wavelet power levels", mar = 4.7))
wt.image(my.w9, color.key = "quantile", n.levels = 250,
legend.params = list(lab = "wavelet power levels", mar = 4.7))


```



